name = "BQ_question_analyzer"

# Install packages to be used in this project
# Standard Libraries to include
#-> csv - writing our findings to a CSV file
#-> io - converting raw input into something we can work with
#-> js - working with javascript-related files (like html)
#-> re - regular expressions
packages = ["pandas", "PyPDF2", "python-docx", "striprtf"]


# Fetch arbitrary content from URLs onto the virtual filesystem, just map a valid
# URL to a destination in the filesystem path
[files]
"./a_GetFileContents.py" = "a_GetFileContents.py"
"./b_SummarizeQuestions.py" = "b_SummarizeQuestions.py"
"./c_AddQuestionNotes.py" = "c_AddQuestionNotes.py"
"./d_AddConcordance.py" = "d_AddConcordance.py"
