name = "BQ_question_analyzer"

# Install packages to be used in this project
# Standard Libraries to include
#-> csv - writing our findings to a CSV file
#-> io - converting raw input into something we can work with
#-> js - working with javascript-related files (like html)
#-> re - regular expressions
packages = ["pandas", "PyPDF2", "python-docx"]


# Fetch arbitrary content from URLs onto the virtual filesystem, just map a valid
# URL to a destination in the filesystem path
[files]
"https://layne_maple_r3.pyscriptapps.com/bq-question-analyzer/latest/a_GetFileContents.py" = "a_GetFileContents.py"
"https://layne_maple_r3.pyscriptapps.com/bq-question-analyzer/latest/b_SummarizeQuestions.py" = "b_SummarizeQuestions.py"
"https://layne_maple_r3.pyscriptapps.com/bq-question-analyzer/latest/c_AddQuestionNotes.py" = "c_AddQuestionNotes.py"
"https://layne_maple_r3.pyscriptapps.com/bq-question-analyzer/latest/d_AddConcordance.py" = "d_AddConcordance.py"
